Header header

geometry_msgs/Vector3 position

geometry_msgs/Vector3 velocity

geometry_msgs/Quaternion orientation

geometry_msgs/Vector3 accleration_bias

geometry_msgs/Vector3 angularvelocity_bias

float64[] covariance

bool is_initialized





# Details of dependencies

# geometry_msgs/Quaternion

## This represents an orientation in free space in quaternion form.
#
#float64 x
#float64 y
#float64 z
#float64 w
