general:

  # node names
  locator_node_name: 'locator'

  # output data topics
  state_topic: '/kalani/state' # type: nav_msgs/Odometry

  # tf ids for output data
  tf_frame_world: 'world'
  tf_frame_map: 'map'
  tf_frame_odom: 'odom'
  tf_frame_state: 'base_link'

  # tf child frame ids for processed data
  tf_frame_gnss: 'gnss'
  tf_frame_magneto: 'magneto'
  tf_frame_groundtruth: 'gt'

  # processed data topics
  processed_gnss_topic: '/kalani/processed_data/gnss' # type: nav_msgs/Odometry
  processed_altitude_topic: '/kalani/processed_data/altitude' # type: nav_msgs/Odometry
  processed_imu_topic: '/kalani/processed_data/imu' # type: sensor_msgs/Imu
  processed_magneto_topic: '/kalani/processed_data/magneto' # type: sensor_msgs/MagneticField
  processed_odometry_topic: '/kalani/processed_data/odometry' # type: nav_msgs/Odometry
  processed_laserodom_topic: '/kalani/processed_data/laserodom' # type: nav_msgs/Odometry
  processed_visualodom_topic: 'kalani/processed_data/visualodom' # type: nav_msgs/Odometry

  # tf frame ids for sensors
  tf_frame_gnss_receiver: 'gnss_receiver'
  tf_frame_altimeter: 'altimeter'
  tf_frame_imu: 'imu'
  tf_frame_magnetometer: 'magnetometer'
  tf_frame_odometer: 'odometer'
  tf_frame_lidar: 'lidar'
  tf_frame_camera: 'camera'


kalman_filter:
  buffer_size: 50 # State buffer length
  state_init_time_threshold: 1 # Allowed maximum gap between any two initial state variables (in seconds)
  gravity: 9.8 # Gravitational acceleration (in m s^-2)


nclt_dataset:
  feeder_node_name: 'nclt_feeder'
  evaluator_node_name: 'nclt_evaluator'

  # info of current dataset to use
  data_root: '/home/pasan/kalani-data/nclt'
  sequence: '2012-04-29'

  # common info
  file_name_imu: 'ms25.csv'
  file_name_gnss: 'gps.csv'
  file_name_groundtruth: 'groundtruth.csv'
  file_name_lidar_hits: 'velodyne_hits.bin'
  dir_name_lidar_sync: 'velodyne_sync'
  map_origin_gnss_coordinates: # in degrees
    lat: 478787
    lon: 12121
    alt: 0

  # sequence specific info
  2012-04-29:
    time_start_motion: 1335704128.61069  # in seconds


kaist_dataset:
  feeder_node_name: 'kaist_feeder'
  evaluator_node_name: 'kaist_evaluator'

  # info of current dataset to use
  data_root: '/home/pasan/kalani-data/kaist'
  sequence: 'urban17'

  # common info
  file_name_imu: 'data/xsens_imu.csv'
  file_name_gnss: 'data/gps.csv'
  file_name_altimeter: 'data/altimeter.csv'
  file_name_groundtruth: 'pose/global_pose.csv'
  dir_left_lidar: 'data/VLP_LEFT'

  # sequence specific info
  urban17:
    time_start_motion: 1335704128.61069  # in seconds
    map_origin_gnss_coordinates: # in degrees
      lat: 478787
      lon: 12121
      alt: 0